[package]
name = "ketupa"
version = "0.1.0"
edition = "2021"

[dependencies]
mint = "0.5"
num-traits = "0.2"

[dev-dependencies]
ketupa_demo_engine = { git = "https://github.com/30bit/ketupa_demo_engine" }
glam = { version = "0.20", features = ["serde"] }
clipboard = "0.5"
serde_json = "1.0"
